name = "Lox macro"
description = "Analyze your Lox source code."

# Leave these as-is
version = "1"
category = "language"
visibility = "public"

[analyzer]
  command = "python3 /app/main.py"

[build]
  image = "python:3.10.2-slim-buster"
  steps = """
  cp -R . /app
  python3 -m pip install mypylox
  """
